apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: build

on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - '**'

jobs:
  java-build:
    steps:
      - name: checkout
        uses: cloudbees-io/checkout@v1
      - name: mvn install
        uses: docker://maven:3.9-eclipse-temurin-21-alpine
        run: mvn verify
